const constants = {
  ADD_TEAM: "ADD_TEAM",
  ADD_PLAYER: "ADD_PLAYER",
  REMOVE_PLAYER: "REMOVE_PLAYER",
  ADD_PLAYER_NOTE: "ADD_PLAYER_NOTE",
  REMOVE_PLAYER_NOTE: "REMOVE_PLAYER_NOTE",
  ADD_TEAM_NOTE: "ADD_TEAM_NOTE",
  REMOVE_TEAM_NOTE:  "REMOVE_TEAM_NOTE",
  ADD_GAME_DATE: "ADD_GAME_DATE",
  ADD_OPPONENT: "ADD_OPPONENT"
}

export default constants
