const constants = {
  ADD_TEAM: "ADD_TEAM",
  ADD_PLAYER: "ADD_PLAYER",
  IS_STARTER: "IS_STARTER",
  PLAYER_NOTES: "PLAYER_NOTES",
  TEAM_NOTES: "TEAM_NOTES",
  GAME_DATE: "GAME_DATE",
  OPPONENT: "OPPONENT"
}
